{% set name = "pegen" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pegen-{{ version }}.tar.gz
  sha256: 0cd306d5b1073542c177035c3caa4526cd10f674a74d6ab40d9a94c57fe1ff33

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - setuptools >=61.2
    - wheel
    - setuptools-scm >=3.4.3
    - pip
  run:
    - python >=3.8,<4.0

test:
  imports:
    - pegen
  commands:
    - pip check
  requires:
    - pip

about:
  summary: CPython's PEG parser generator
  license: MIT
  license_file: LICENSE
  home: https://we-like-parsers.github.io/pegen/

extra:
  recipe-maintainers:
    - gabrielcnr 
    - MatthieuDartiailh
    - marcelotrevisani
